// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Quote(text string, author string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<blockquote><svg class=\"quote-svg\" width=\"12\" height=\"12\" viewBox=\"0 0 12 12\" fill=\"none\" aria-hidden=\"true\" version=\"1.1\" id=\"quote-svg\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:svg=\"http://www.w3.org/2000/svg\"><path d=\"m 5.4018188,8.4102461 c 0,0.6966757 -0.224093,1.2612776 -0.6722789,1.6937159 -0.448186,0.408384 -1.0143195,0.612621 -1.6983915,0.612621 -0.8256143,0 -1.5096951,-0.27631 -2.0522428,-0.8288403 C 0.459953,9.3351229 0.20048119,8.5424099 0.20048119,7.5093245 c 0,-1.1051224 0.30665261,-2.1862174 0.91995791,-3.2432852 0.6369091,-1.0810951 1.5214881,-1.933962 2.653755,-2.5585917 L 4.5880064,2.9687251 C 3.9747013,3.4011632 3.4793345,3.8816469 3.1019151,4.4101853 2.7480818,4.9387237 2.5121868,5.5513442 2.3942483,6.248047 c 0.2123,-0.0961 0.459979,-0.144146 0.7430457,-0.144146 0.660486,0 1.2030336,0.2162189 1.6276247,0.648657 0.4246001,0.432438 0.6369001,0.9850037 0.6369001,1.6576881 z m 6.5105182,0 c 0,0.6966757 -0.224057,1.2612776 -0.672262,1.6937159 -0.448203,0.408384 -1.014337,0.612621 -1.6984001,0.612621 -0.8255969,0 -1.5096599,-0.27631 -2.0522434,-0.8288403 C 6.9704788,9.3351229 6.7109979,8.5424099 6.7109979,7.5093245 c 0,-1.1051224 0.3066527,-2.1862174 0.9199669,-3.2432852 0.6369091,-1.0810951 1.5215156,-1.933962 2.6537822,-2.5585917 l 0.813794,1.2612775 C 10.4852,3.4011632 9.9898789,3.8816469 9.6123959,4.4101853 9.2586079,4.9387237 9.0227486,5.5513442 8.9047291,6.248047 9.1170745,6.151947 9.3647349,6.103901 9.6478019,6.103901 c 0.6604591,0 1.2030791,0.2162189 1.6276791,0.648657 0.4246,0.432438 0.636856,0.9850037 0.636856,1.6576881 z\" fill=\"currentColor\" id=\"quote-svg-path\"></path></svg><div class=\"quote-text-wrapper\"><em>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(text)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/quote.templ`, Line: 23, Col: 22}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</em></div><footer>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(author)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/quote.templ`, Line: 25, Col: 24}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</footer></blockquote>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
